name: Waka Readme

on:
  schedule:
    # Runs every 11:30 UTC or 18:30 Jakarta time
    - cron: '30 11 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_COMMIT: False
          SHOW_PROFILE_VIEWS: False
          SHOW_EDITORS: False
